services:
  - type: web
    name: hasta-randevu-takip
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ConnectionStrings__DefaultConnection
        fromDatabase:
          name: hasta-randevu-db
          property: connectionString

databases:
  - name: hasta-randevu-db
    plan: free
    databaseName: hastarandevutakipdb

